#!/bin/bash -x
if [[ -z $1 ]]; then
    echo "Please specify a PID as the first argument to $0" >&2
    exit 1
else
    PID=$1
    echo "Inspecting $PID ..." >&2
fi

PY_VER=`/proc/$PID/exe -c 'import sys; print("%d.%d" % (sys.version_info[0], sys.version_info[1]))'`
if [[ -z $PY_VER ]]; then
    echo "Could not determine which version of python $PID is using."
    exit 1
fi

if ! dpkg -l python${PY_VER}-dbg >/dev/null; then
    echo "Fetching debug packages..."
    sudo apt-get -y install python${PY_VER}-dbg
fi

sudo gdb -q /usr/bin/python${PY_VER} -p $PID -ex bt -ex 'printf "\n=============\n\n"' \
  -ex py-locals \
  -ex 'printf "\n=============\n\n"' \
  -ex py-list \
  -ex 'printf "\n=============\n\n"' \
  -ex py-bt \
  -ex quit </dev/null
